### ISSUE TITLE
Support for ESP32 S2 mini boards

### ISSUE THREAD

**Issue by suriaribeiro** [AWSW-de/WordClock-16x16-LED-matrix-2023#12]
Hello, love the project. I been trying to get this running on a ESP32 S2 mini board and despite my best efforts the application does not seem to start after uploading the code. 
Is there something specific that needs to be done to the code so that it can work with the newer ESP32 boards? 

Full disclosure, the flashing works fine with just a small issue at the end: "Leaving...
WARNING: ESP32-S2FNR2 (revision v1.0) chip was placed into download mode using GPIO0.
esptool.py can not exit the download mode over USB. To run the app, reset the chip manually.
To suppress this note, set --after option to 'no_reset'.
Failed uploading: uploading error: exit status 1"

**Comment by AWSW-de** [comment]
Hello,
thank you for the nice words. =)

I honestly have not tried these newer ESP32 boards yet, so I cannot say why it is not working for you. 

I would suggest sticking with the named to use ESP32 D1 mini board as long as they are produced, because with these I tested all functions and I would not to like to open up such fragmentations by supporting several boards which will cause a lot of extra development and testing on my side and will not help to make the project better. As long as the “old” ESP32 are more then capable enough to run the project I will not think about switching the board. 

Hope this helps you. =) 

Kind regards
AWSW
