### ISSUE TITLE
Changing time zone from web interface

### ISSUE THREAD

**Issue by gcseed** [AWSW-de/WordClock-16x16-LED-matrix-2023#2]
Hello, I'm reaching out to inquire if there's a way to modify the time zone settings through the web interface, without the need to reconnect the board to a computer. Any guidance or instructions on this matter would be greatly appreciated.

Additionally, I'd like to express my gratitude for the outstanding performance of the clock. It has truly exceeded my expectations, and thank you for the exceptional work you have put into this remarkable product.

**Comment by AWSW-de** [comment]
Hello,
thanks for your nice words. =)

Currently I am not planning to add such 1-time settings to the web interface, because the memory on these boards is very limited and such large drop-down lists would bring down the performance of the web interface a lot due to some earlier done tests. Because you usually set this once this should not be a problem to change in Arduino and then there is no need to have it in the web interface again…

Kind regards
